spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    content-type: text/html
    mode: HTML5
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC